version: "3.1"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  app:
    build: .
    depends_on:
      - db
    links:
      - db
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
